[package]
name = "gstreamer-terminal-video-player"
version = "0.1.0"
edition = "2021"

[dependencies]
gstreamer = "0.23.4"
glib = "0.20.7"
gstreamer-app = "0.23.4"
flume = "0.11.1"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26.0"
objc = "0.2.7"